# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='author',
            field=models.CharField(default='bryan', max_length=141),
        ),
    ]
