# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20171002_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authored_on',
            new_name='authored',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='authored_on',
            new_name='authored',
        ),
    ]
