# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20171004_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='authored',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='authored',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
