# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20171006_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='idescription',
            field=models.CharField(default='Image not found', max_length=144),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='image',
            field=models.ImageField(default='', max_length=144, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
